version: "3.9"

services:
  simplegrants-frontend:
    container_name: simplegrants-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
    restart: always
    env_file:
      - .env.local
    ports:
      - 3001:3001
    networks:
      - simplegrants

networks:
  simplegrants:
