services:
  simplegrants-backend:
    container_name: simplegrants-backend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: on-failure
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - simplegrants

  simplegrants-database:
    container_name: simplegrants-database
    image: postgres:14
    restart: on-failure
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - simplegrants-database:/var/lib/postgresql/data
      - ./letsencrypt/archive/npm-2:/etc/ssl/postgres:ro # 鍵ファイルをマウント
    networks:
      - simplegrants
    entrypoint: >
      /bin/sh -c "
      cp /etc/ssl/postgres/fullchain1.pem /var/lib/postgresql/server.crt &&
      cp /etc/ssl/postgres/privkey1.pem /var/lib/postgresql/server.key &&
      chown postgres:postgres /var/lib/postgresql/server.* &&
      chmod 600 /var/lib/postgresql/server.key &&
      docker-entrypoint.sh -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
      "

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - simplegrants

volumes:
  simplegrants-database:

networks:
  simplegrants: